sudo: required
addons:
  hosts:
    - pomodoro.dev
language: ruby
services:
  - docker
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
before_install:
  - opt/bootstrap
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
script:
  - app/opt/test
  - opt/docker.build
  - auth/opt/test
  - api/opt/test
  - opt/docker.run DEV
  - opt/docker.seed
  - acceptance-tests/opt/test
deploy:
  skip_cleanup: true
  provider: script
  script: opt/deploy
  on:
    branch: master

notifications:
  webhooks:
    - https://xcdfvwjvr8.execute-api.eu-west-1.amazonaws.com/pro/travis/notification
