version: 2

# build job parameters as a template
defaults: &defaults
  working_directory: ~/pomodoro.cc
  docker:
    - image: cypress/base:8
      environment:
        TERM: xterm
    - image: mongo:3.4

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: pwd
      - run: ls
      - restore_cache:
          keys:
          - v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          - v2-deps-{{ .Branch }}-
          - v2-deps-
      - run: npm install
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: cd app ; npm install
      - run: cd api ; npm install
      - persist_to_workspace:
          root: ~/
          paths:
            - .cache
            - pomodoro.cc

  test_app:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: test_app
          command: |
            cd app
            npm t

  test_api:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: test_api
          command: |
            npm cache clean -f || exit 0
            # npm i -g --unsafe-perm now
            npm install -g --unsafe-perm now@canary
            npm i -g wait-on
            cd api
            echo -e "NODE_ENV=test\nTWITTER_CONSUMER_KEY=\nTWITTER_CONSUMER_SECRET=\nTWITTER_CALLBACK_URL=\nGITHUB_CLIENT_ID=\nGITHUB_CLIENT_SECRET=\nGITHUB_CALLBACK_URL=\nMONGO_URL=mongodb://127.0.0.1:27017/test\nHOST=api.pomodoro.cc\nPUSHER_APP_ID=\nPUSHER_KEY=\nPUSHER_SECRET=\nSENTRY_DSN=\nSTRIPE_SECRET_KEY=''\nSTRIPE_PLAN=''\nUSE_AUTH=false\nBASE_URL=http://localhost:3000\nLEVEL=info" > .env
            now dev --token $NOW_TOKEN & wait-on http://localhost:3000
            npm t

  uat:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: uat
          command: |
            npm i -g wait-on
            cd app
            npm i cypress
            npm start & wait-on http://localhost:1234
            npm run cypress -- run

  deploy_app:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: deploy app
          command: |
            npm install -g --unsafe-perm now@canary
            # npm i -g --unsafe-perm now
            cd app
            npm run deploy --silent -- --token $NOW_TOKEN

  deploy_api:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: deploy api
          command: |
            npm install -g --unsafe-perm now@canary
            # npm i -g --unsafe-perm now
            cd api
            npm run deploy --silent -- --token $NOW_TOKEN

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_app:
          requires:
            - build
      - test_api:
          requires:
            - build
      - uat:
          requires:
            - build
      - deploy_app:
          requires:
            - test_app
            - test_api
            - uat
      - deploy_api:
          requires:
            - test_app
            - test_api
            - uat