version: 2

# build job parameters as a template
defaults: &defaults
  working_directory: ~/pomodoro.cc
  docker:
    - image: cypress/base:8
      environment:
        TERM: xterm

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: pwd
      - run: ls
      - restore_cache:
          keys:
          - v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          - v2-deps-{{ .Branch }}-
          - v2-deps-
      - run: npm install
      - save_cache:
          key: v2-deps-{{ .Branch }}-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
            - ~/.cache
      - run: cd app ; npm install
      - run: cd api ; npm install
      - persist_to_workspace:
          root: ~/
          paths:
            - .cache
            - pomodoro.cc

  test_app:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: test_app
          command: |
            cd app
            npm t
  test_auth:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: test_auth
          command: |
            npm i -g wait-on
            cd api
            now dev --token $NOW_TOKEN & wait-on http://localhost:3000
            npm t

  uat:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: uat
          command: |
            npm i -g wait-on
            cd app
            npm start & wait-on http://localhost:1234
            npm run cypress -- run

  deploy_app:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: deploy app
          command: |
            npm i -g --unsafe-perm now
            cd app
            npm run deploy --silent -- --token $NOW_TOKEN

  deploy_auth:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/
      - run:
          name: deploy api
          command: |
            npm i -g --unsafe-perm now
            cd api
            npm run deploy --silent -- --token $NOW_TOKEN

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test_app:
          requires:
            - build
      - uat:
          requires:
            - test_app
      - deploy_app:
          requires:
            - uat
      - deploy_auth:
          requires:
            - uat