version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - run:
          name: Install app deps
          command: |
            cd app
            npm i
            npm i -g now
      - cypress/install:
          build: 'cd app ; npm run build'  # run a custom app build step
      - cypress/run:
          requires:
            - cypress/install
          record: false        # record results on Cypress Dashboard
          parallel: false      # split all specs across machines
          group: 'pomodoro.cc'  # name this group "all tests" on the dashboard
          start: 'now dev'  # start server before running tests
      - run:
          name: app tests
          command: |
            cd app
            npm t
